In [302]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import warnings
warnings.filterwarnings('ignore')

In [303]:
path = '/content/archive (9).zip'
data = pd.read_csv(path)

In [304]:
data.head(10)

id first_name  last_name                                  email  gender  \
0   1       Paul      Casey         paul.casey.1@gslingacademy.com    male   
1   2   Danielle   Sandoval  danielle.sandoval.2@gslingacademy.com  female   
2   3       Tina    Andrews       tina.andrews.3@gslingacademy.com  female   
3   4       Tara      Clark         tara.clark.4@gslingacademy.com  female   
4   5    Anthony     Campos     anthony.campos.5@gslingacademy.com    male   
5   6      Kelly       Wade         kelly.wade.6@gslingacademy.com  female   
6   7    Anthony      Smith      anthony.smith.7@gslingacademy.com    male   
7   8     George      Short       george.short.8@gslingacademy.com    male   
8   9    Stanley  Gutierrez  stanley.gutierrez.9@gslingacademy.com    male   
9  10     Audrey    Simpson    audrey.simpson.10@gslingacademy.com  female   

   part_time_job  absence_days  extracurricular_activities  \
0          False             3                       False   
1          False             2                       False   
2          False             9                        True   
3          False             5                       False   
4          False             5                       False   
5          False             2                       False   
6          False             3                        True   
7           True             2                        True   
8          False             6                       False   
9          False             3                        True   

   weekly_self_study_hours   career_aspiration  math_score  history_score  \
0                       27              Lawyer          73             81   
1                       47              Doctor          90             86   
2                       13  Government Officer          81             97   
3                        3              Artist          71             74   
4                       10             Unknown          84             77   
5                       26             Unknown          93            100   
6                       23   Software Engineer          99             96   
7                       34   Software Engineer          95             95   
8                       25             Unknown          94             68   
9                       18             Teacher          98             69   

   physics_score  chemistry_score  biology_score  english_score  \
0             93               97             63             80   
1             96              100             90             88   
2             95               96             65             77   
3             88               80             89             63   
4             65               65             80             74   
5             67               78             72             80   
6             97               73             88             76   
7             82               63             84             70   
8             94               85             81             74   
9             88               71             67             71   

   geography_score  
0               87  
1               90  
2               94  
3               86  
4               76  
5               84  
6               64  
7               85  
8               72  
9               73

In [305]:
data.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'part_time_job',
       'absence_days', 'extracurricular_activities', 'weekly_self_study_hours',
       'career_aspiration', 'math_score', 'history_score', 'physics_score',
       'chemistry_score', 'biology_score', 'english_score', 'geography_score'],
      dtype='object')

In [306]:
data.isnull().sum()

id                            0
first_name                    0
last_name                     0
email                         0
gender                        0
part_time_job                 0
absence_days                  0
extracurricular_activities    0
weekly_self_study_hours       0
career_aspiration             0
math_score                    0
history_score                 0
physics_score                 0
chemistry_score               0
biology_score                 0
english_score                 0
geography_score               0
dtype: int64

In [307]:
data.describe()

id  absence_days  weekly_self_study_hours   math_score  \
count  2000.000000   2000.000000              2000.000000  2000.000000   
mean   1000.500000      3.665500                17.755500    83.452000   
std     577.494589      2.629271                12.129604    13.224906   
min       1.000000      0.000000                 0.000000    40.000000   
25%     500.750000      2.000000                 5.000000    77.000000   
50%    1000.500000      3.000000                18.000000    87.000000   
75%    1500.250000      5.000000                28.000000    93.000000   
max    2000.000000     10.000000                50.000000   100.000000   

       history_score  physics_score  chemistry_score  biology_score  \
count    2000.000000    2000.000000      2000.000000     2000.00000   
mean       80.332000      81.336500        79.995000       79.58150   
std        12.736046      12.539453        12.777895       13.72219   
min        50.000000      50.000000        50.000000       30.00000   
25%        69.750000      71.000000        69.000000       69.00000   
50%        82.000000      83.000000        81.000000       81.00000   
75%        91.000000      92.000000        91.000000       91.00000   
max       100.000000     100.000000       100.000000      100.00000   

       english_score  geography_score  
count    2000.000000      2000.000000  
mean       81.277500        80.888000  
std        12.027087        11.637705  
min        50.000000        60.000000  
25%        72.000000        71.000000  
50%        83.000000        81.000000  
75%        91.000000        91.000000  
max        99.000000       100.000000

In [308]:
data.head()

id first_name last_name                                  email  gender  \
0   1       Paul     Casey         paul.casey.1@gslingacademy.com    male   
1   2   Danielle  Sandoval  danielle.sandoval.2@gslingacademy.com  female   
2   3       Tina   Andrews       tina.andrews.3@gslingacademy.com  female   
3   4       Tara     Clark         tara.clark.4@gslingacademy.com  female   
4   5    Anthony    Campos     anthony.campos.5@gslingacademy.com    male   

   part_time_job  absence_days  extracurricular_activities  \
0          False             3                       False   
1          False             2                       False   
2          False             9                        True   
3          False             5                       False   
4          False             5                       False   

   weekly_self_study_hours   career_aspiration  math_score  history_score  \
0                       27              Lawyer          73             81   
1                       47              Doctor          90             86   
2                       13  Government Officer          81             97   
3                        3              Artist          71             74   
4                       10             Unknown          84             77   

   physics_score  chemistry_score  biology_score  english_score  \
0             93               97             63             80   
1             96              100             90             88   
2             95               96             65             77   
3             88               80             89             63   
4             65               65             80             74   

   geography_score  
0               87  
1               90  
2               94  
3               86  
4               76

In [309]:
useless_columns = ['first_name', 'last_name', 'email']
data = data.drop(columns=useless_columns, errors='ignore')


In [310]:
data.head()

id  gender  part_time_job  absence_days  extracurricular_activities  \
0   1    male          False             3                       False   
1   2  female          False             2                       False   
2   3  female          False             9                        True   
3   4  female          False             5                       False   
4   5    male          False             5                       False   

   weekly_self_study_hours   career_aspiration  math_score  history_score  \
0                       27              Lawyer          73             81   
1                       47              Doctor          90             86   
2                       13  Government Officer          81             97   
3                        3              Artist          71             74   
4                       10             Unknown          84             77   

   physics_score  chemistry_score  biology_score  english_score  \
0             93               97             63             80   
1             96              100             90             88   
2             95               96             65             77   
3             88               80             89             63   
4             65               65             80             74   

   geography_score  
0               87  
1               90  
2               94  
3               86  
4               76

In [311]:
data['part_time_job'].unique()

array([False,  True])

In [312]:
print(data['part_time_job'].dtype)


bool


In [313]:
data['part_time_job'] = data['part_time_job'].astype(int)


In [314]:
data['extracurricular_activities'] = data['extracurricular_activities'].astype(int)

In [315]:
print(data['gender'].dtype)
data['gender'] = data['gender'].map({'female': 0, 'male': 1})

object


In [316]:
data.head()

id  gender  part_time_job  absence_days  extracurricular_activities  \
0   1       1              0             3                           0   
1   2       0              0             2                           0   
2   3       0              0             9                           1   
3   4       0              0             5                           0   
4   5       1              0             5                           0   

   weekly_self_study_hours   career_aspiration  math_score  history_score  \
0                       27              Lawyer          73             81   
1                       47              Doctor          90             86   
2                       13  Government Officer          81             97   
3                        3              Artist          71             74   
4                       10             Unknown          84             77   

   physics_score  chemistry_score  biology_score  english_score  \
0             93               97             63             80   
1             96              100             90             88   
2             95               96             65             77   
3             88               80             89             63   
4             65               65             80             74   

   geography_score  
0               87  
1               90  
2               94  
3               86  
4               76

In [317]:
data['career_aspiration'].unique()

array(['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
       'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
       'Banker', 'Writer', 'Accountant', 'Designer',
       'Construction Engineer', 'Game Developer', 'Stock Investor',
       'Real Estate Developer'], dtype=object)

In [318]:
job_titles = ['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
              'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
              'Banker', 'Writer', 'Accountant', 'Designer',
              'Construction Engineer', 'Game Developer', 'Stock Investor',
              'Real Estate Developer']

In [319]:
from sklearn.preprocessing import OneHotEncoder

In [320]:
encoder = OneHotEncoder(sparse_output=False)
job_titles_reshaped = np.array(job_titles).reshape(-1, 1)
one_hot_encoded = encoder.fit_transform(job_titles_reshaped)

In [321]:
print(one_hot_encoded)
data.head()

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


id  gender  part_time_job  absence_days  extracurricular_activities  \
0   1       1              0             3                           0   
1   2       0              0             2                           0   
2   3       0              0             9                           1   
3   4       0              0             5                           0   
4   5       1              0             5                           0   

   weekly_self_study_hours   career_aspiration  math_score  history_score  \
0                       27              Lawyer          73             81   
1                       47              Doctor          90             86   
2                       13  Government Officer          81             97   
3                        3              Artist          71             74   
4                       10             Unknown          84             77   

   physics_score  chemistry_score  biology_score  english_score  \
0             93               97             63             80   
1             96              100             90             88   
2             95               96             65             77   
3             88               80             89             63   
4             65               65             80             74   

   geography_score  
0               87  
1               90  
2               94  
3               86  
4               76

In [322]:
score_data = pd.DataFrame({
    'math_score': [73,90,81,71,84],
    'history_score': [81,86,97,74,77],
    'physics_score': [93,96,95,88,65],
    'chemistry_score': [97,100,96,80,65],
    'biology_score': [63,90,65,89,80],
    'english_score': [80,88,77,63,74],
    'geography_score': [87,90,84,86,76]
})


In [323]:
data['total_score'] = score_data[['math_score', 'history_score', 'physics_score',
                             'chemistry_score', 'biology_score', 'english_score',
                             'geography_score']].sum(axis=1)

In [324]:
data.drop(['math_score', 'history_score', 'physics_score', 'chemistry_score',
           'biology_score', 'english_score', 'geography_score'], axis=1, inplace=True)

In [325]:
data.head()

id  gender  part_time_job  absence_days  extracurricular_activities  \
0   1       1              0             3                           0   
1   2       0              0             2                           0   
2   3       0              0             9                           1   
3   4       0              0             5                           0   
4   5       1              0             5                           0   

   weekly_self_study_hours   career_aspiration  total_score  
0                       27              Lawyer        574.0  
1                       47              Doctor        640.0  
2                       13  Government Officer        595.0  
3                        3              Artist        551.0  
4                       10             Unknown        521.0

In [326]:
data.columns

Index(['id', 'gender', 'part_time_job', 'absence_days',
       'extracurricular_activities', 'weekly_self_study_hours',
       'career_aspiration', 'total_score'],
      dtype='object')

In [327]:
data['part_time_job'] = data['part_time_job'].astype(int)

In [328]:
data.head()

id  gender  part_time_job  absence_days  extracurricular_activities  \
0   1       1              0             3                           0   
1   2       0              0             2                           0   
2   3       0              0             9                           1   
3   4       0              0             5                           0   
4   5       1              0             5                           0   

   weekly_self_study_hours   career_aspiration  total_score  
0                       27              Lawyer        574.0  
1                       47              Doctor        640.0  
2                       13  Government Officer        595.0  
3                        3              Artist        551.0  
4                       10             Unknown        521.0

In [329]:
numeric_data = data.select_dtypes(include='number')
correlation_matrix = numeric_data.corr()
print(correlation_matrix)


                                  id    gender  part_time_job  absence_days  \
id                          1.000000 -0.005808       0.012869     -0.017788   
gender                     -0.005808  1.000000      -0.023809     -0.029357   
part_time_job               0.012869 -0.023809       1.000000      0.206361   
absence_days               -0.017788 -0.029357       0.206361      1.000000   
extracurricular_activities -0.003121 -0.006432      -0.008382      0.029019   
weekly_self_study_hours     0.008524  0.077104      -0.213963     -0.286086   
total_score                -0.684704 -0.581821            NaN     -0.231320   

                            extracurricular_activities  \
id                                           -0.003121   
gender                                       -0.006432   
part_time_job                                -0.008382   
absence_days                                  0.029019   
extracurricular_activities                    1.000000   
weekly_self_study_h

In [330]:
data = pd.get_dummies(data, columns=['career_aspiration'], drop_first=True)

In [331]:
data.columns

Index(['id', 'gender', 'part_time_job', 'absence_days',
       'extracurricular_activities', 'weekly_self_study_hours', 'total_score',
       'career_aspiration_Artist', 'career_aspiration_Banker',
       'career_aspiration_Business Owner',
       'career_aspiration_Construction Engineer', 'career_aspiration_Designer',
       'career_aspiration_Doctor', 'career_aspiration_Game Developer',
       'career_aspiration_Government Officer', 'career_aspiration_Lawyer',
       'career_aspiration_Real Estate Developer',
       'career_aspiration_Scientist', 'career_aspiration_Software Engineer',
       'career_aspiration_Stock Investor', 'career_aspiration_Teacher',
       'career_aspiration_Unknown', 'career_aspiration_Writer'],
      dtype='object')

In [332]:
new_cols = ['career_aspiration_Artist', 'career_aspiration_Banker',
       'career_aspiration_Business Owner',
       'career_aspiration_Construction Engineer', 'career_aspiration_Designer',
       'career_aspiration_Doctor', 'career_aspiration_Game Developer',
       'career_aspiration_Government Officer', 'career_aspiration_Lawyer',
       'career_aspiration_Real Estate Developer',
       'career_aspiration_Scientist', 'career_aspiration_Software Engineer',
       'career_aspiration_Stock Investor', 'career_aspiration_Teacher',
       'career_aspiration_Unknown', 'career_aspiration_Writer']

In [333]:
data[new_cols] = data[new_cols].astype(int)

In [334]:
data.head()

id  gender  part_time_job  absence_days  extracurricular_activities  \
0   1       1              0             3                           0   
1   2       0              0             2                           0   
2   3       0              0             9                           1   
3   4       0              0             5                           0   
4   5       1              0             5                           0   

   weekly_self_study_hours  total_score  career_aspiration_Artist  \
0                       27        574.0                         0   
1                       47        640.0                         0   
2                       13        595.0                         0   
3                        3        551.0                         1   
4                       10        521.0                         0   

   career_aspiration_Banker  career_aspiration_Business Owner  ...  \
0                         0                                 0  ...   
1                         0                                 0  ...   
2                         0                                 0  ...   
3                         0                                 0  ...   
4                         0                                 0  ...   

   career_aspiration_Game Developer  career_aspiration_Government Officer  \
0                                 0                                     0   
1                                 0                                     0   
2                                 0                                     1   
3                                 0                                     0   
4                                 0                                     0   

   career_aspiration_Lawyer  career_aspiration_Real Estate Developer  \
0                         1                                        0   
1                         0                                        0   
2                         0                                        0   
3                         0                                        0   
4                         0                                        0   

   career_aspiration_Scientist  career_aspiration_Software Engineer  \
0                            0                                    0   
1                            0                                    0   
2                            0                                    0   
3                            0                                    0   
4                            0                                    0   

   career_aspiration_Stock Investor  career_aspiration_Teacher  \
0                                 0                          0   
1                                 0                          0   
2                                 0                          0   
3                                 0                          0   
4                                 0                          0   

   career_aspiration_Unknown  career_aspiration_Writer  
0                          0                         0  
1                          0                         0  
2                          0                         0  
3                          0                         0  
4                          1                         0  

[5 rows x 23 columns]

In [335]:
# Check for missing values
print(data.isnull().sum())

# Handle missing values (example: fill NaNs with the mean of the column)
data = data.fillna(data.mean())


id                                            0
gender                                        0
part_time_job                                 0
absence_days                                  0
extracurricular_activities                    0
weekly_self_study_hours                       0
total_score                                1995
career_aspiration_Artist                      0
career_aspiration_Banker                      0
career_aspiration_Business Owner              0
career_aspiration_Construction Engineer       0
career_aspiration_Designer                    0
career_aspiration_Doctor                      0
career_aspiration_Game Developer              0
career_aspiration_Government Officer          0
career_aspiration_Lawyer                      0
career_aspiration_Real Estate Developer       0
career_aspiration_Scientist                   0
career_aspiration_Software Engineer           0
career_aspiration_Stock Investor              0
career_aspiration_Teacher               

In [336]:
X = data.drop(['total_score'], axis=1)
y = data['total_score']

In [337]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [344]:
from sklearn import preprocessing
scale = preprocessing.StandardScaler()

X_train = scale.fit_transform(X_train)
X_test = scale.transform(X_test)

y_train = scale.fit_transform(y_train.values.reshape(-1, 1))  # Reshaping for a single feature
y_test = scale.transform(y_test.values.reshape(-1, 1))

In [345]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)


LinearRegression()

In [346]:
y_pred = model.predict(X_test)
from sklearn.metrics import mean_squared_error, r2_score
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R-squared:", r2_score(y_test, y_pred))


Mean Squared Error: 0.01804685902904638
R-squared: -1.132819701295058e+56


In [347]:
model.score(X_test,y_test)

-1.132819701295058e+56